
main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Experience
    url: '#experience'
    weight: 20
  - name: Publications
    url: "/publication/"
    weight: 30
  - name: Conferences
    url: "/conf/"
    weight: 40
  - name: Working Papers
    url: "/working/"
    weight: 50
  - name: Published Essays
    url: '/essays/'
    weight: 60
  - name: Press
    url: '/press/'
    weight: 70
  - name: Resources
    url: '/resources/'
    weight: 80
  - name: Contact
    url: '#contact'
    weight: 90
