# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Experience
    url: '#experience'
    weight: 20
  - name: Publications
    url: '#pubs'
    weight: 30
  - name: Popular Press
    url: '#posts'
    weight: 40
  - name: Preprints
    url: '#featured'
    weight: 50
  - name: Videos
    url: '#gallery'
    weight: 60
  - name: Contact
    url: '#contact'
    weight: 70
