
main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Experience
    url: '#experience'
    weight: 20
  - name: Research Output
    url: "/resout/"
    weight: 30
  - name: Essays
    url: '/essays/'
    weight: 60
  - name: Press
    url: '/press/'
    weight: 70
  - name: Resources
    url: '/resources/'
    weight: 80
  - name: Contact
    url: '#contact'
    weight: 90
