
main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Experience
    url: '#experience'
    weight: 20
  - name: Research Output
    url: '#output'
    weight: 30
  - name: Essays
    url: '#popp'
    weight: 60
  - name: Press
    url: '#ft'
    weight: 70
  - name: Resources
    url: '#resources'
    weight: 80
  - name: Contact
    url: '#contact'
    weight: 90
