---
title: "Research Output"
mainfont: Times New Roman
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
---

<center> <h1>Peer-Reviewed Publications </h1></center>

<ol>
<li>Kapoor, H., Rezaei, S., Gurjar, S., Tagat, A., George, D, Budhwar, Y. & **Puthillam, A.** (2023). Does incentivization promote sharing “true” content online?. _HKS Misinformation Review_. [https://doi.org/10.37016/mr-2020-120](https://doi.org/10.37016/mr-2020-120])</li>

<li>**Puthillam, A.**, Montilla Doble, L. J., Delos Santos, J. I., Elsherif, M. M., Steltenpohl, C. N., Moreau, D.,...& Kapoor, H. (2023). Guidelines to Improve Internationalization in the Psychological Sciences. _Personality and Social Psychology Compass_. [https://doi.org/10.1111/spc3.12847](https://doi.org/10.1111/spc3.12847)</li>

<li>**Puthillam, A.** (2023). Too WEIRD, Too Fast? Preprints about COVID-19 in Psychology. _Collabra: Psychology_. [https://doi.org/10.1525/collabra.74331](https://doi.org/10.1525/collabra.74331)</li>

<li>. Azevedo, F.,... **Puthillam, A.**...Sampaio, W. M. (2023). Social and moral psychology of COVID-19 across 69 countries. _Scientific Data_.[https://doi.org/10.1038/s41597-023-02080-8](https://doi.org/10.1038/s41597-023-02080-8)</li> 

<li> Pavlović, T.... **Puthillam, A.**... van Bavel, J. (2022). Predicting attitudinal and behavioral responses to COVID-19 pandemic using machine learning. _PNAS Nexus_. [https://doi.org/10.1093/pnasnexus/pgac093](https://doi.org/10.1093/pnasnexus/pgac093)</li>

<li> van Bavel et al (2022). National identity predicts public health support during a global pandemic. _Nature Communications_. [https://doi.org/10.1038/s41467-021-27668-9](https://doi.org/10.1038/s41467-021-27668-9)</li>

<li> **Puthillam, A.**, Parekh, A., & Kapoor, H. (2021). How do relationships to victims and perpetrators affect the advice to report rape in India? _Violence against Women_. [https://doi.org/10.1177/10778012211005565](https://doi.org/10.1177/10778012211005565)</li>

<li> **Puthillam, A.**, Parekh, A., Karandikar, S., Kapoor, H. (2021). Gratitude blindness: How does the dark triad experiences gratitude? _Personality and Individual Differences_, 168, 110309. [https://doi.org/10.1016/j.paid.2020.110309](https://doi.org/10.1016/j.paid.2020.110309)</li>

<li> **Puthillam, A.**, & Karandikar, S. (2020). Watching disgustedly? Game of Thrones and disgust sensitivity. _Psychological Reports_. [https://doi.org/10.1177/0033294120957245](https://doi.org/10.1177/0033294120957245)</li>

<li> **Puthillam, A.**, Karandikar, S., & Kapoor, H. (2019). I see how you feel: How the dark triad recognizes emotions. _Current Psychology_, 1-8. [doi:10.1007/s12144-019-00359-x](doi:10.1007/s12144-019-00359-x)</li>

<li> Debnath, A., Phansikar, M., **Puthillam, A.***, & Sengupta, P. (2016). Cross sectional analysis of gender atypical behaviours. _Social Sciences International Research Journal_ 2(1), 378-381.</li>

*Authors contributed equally to the work. Authorship order determined appear alphabetically

</ol>

<center> <h1> Conference Presentations </h1></center>

<ol>
<li> Kapoor, H., Rezaei, S., Gurjar, S., Tagat, A., George, D., Budhwar,Y. & **Puthillam, A**. (2023, February). Does Incentivization Promote Sharing of “Good” Content Online? [Poster] Society for Social and Personality Psychology.</li> 

<li> Mahadeshwar, H., Mehta, N., Gurjar, S., Kapoor, H., & **Puthillam, A**. (2023, February). . Does Incentivization Promote Sharing of “Good” Content Online? [Poster] Society for Social and Personality Psychology.</li> 

<li> **Puthillam, A.** & Kapoor, H. (2022, July). Social and personality correlates of political ideology in India. Paper to be presented at the _Annual Meeting of the International Society for Political Psychology_ [virtual].</li>

<li> **Puthillam, A.** & Kapoor, H. (2022, July). Partisanship and vaccine hesitancy in India. Blitz to be presented at the _Annual Meeting of the International Society for Political Psychology_ [virtual]</li>

<li> Ghai, S., Adetula, A., **Puthillam, A.**, Salvador, C., Kapoor, H., Atari, M., Saab, R (2022, June). A global diversity hackathon: Crowdsourcing diverse perspectives from the global south. [Hackathon] at the Society for the Improvement of Psychological Science meeting, 2022. [virtual]</li> 

<li> **Puthillam, A**. & Kapoor, H. (2022, February). Partisanship and mobility behaviours during COVID-19 in India. [Poster]. _2022 SPSP Virtual Annual Convention_. [virtual]</li>

<li> Ticku, A., et al (2022, February). Pro-environmental behaviors. [Poster] _SPSP Virtual Annual Convention 2022_. [virtual]</li>

<li> **Puthillam, A.** & Kapoor, H. (2021, November). Beyond left and right: Political psychology in India. [Poster] _Harvard Women in Psychology Trends in Psychology Summit_. [virtual]</li>

<li> **Puthillam, A.**, & Kapoor, H. (2021, October). Who cares about the outgroup? Political Ideology, Intergroup Empathy, and Moral Decision-Making. Cross-country [Proposal] _Psychological Science Accelerator Conference 2021_ [(Preregistration)](https://osf.io/sfh93)</li>

<li> Montilla, J., **Puthillam, A.**, Kapoor, H. (2021, October). Guidelines on including non-WEIRD populations in psychological science. Paper to be presented at the 60th Annual Conference of the Taiwan Psychological Association [based on a previous hackathon] [Hackathon Materials](https://osf.io/vm3sd/)</li> 

<li> **Puthillam, A.** & Kapoor, H. (2021, October). Role of psychology in combating misinformation. Conversation at _The Centre for Internet and Society’s Seminar Series on Information Disorders_.</li>


<li> **Puthillam, A.**, & Kapoor, H. (2021, July). They caused the pandemic! The mediating role of conspiratorial blame on the relationship between political ideology and risk perception. [Symposium Presentation]_2021 Annual Scientific Meeting of the International Society of Political Psychology_ [(Preregistration)](https://osf.io/td39c/)</li>

<li> **Puthillam, A.**, & Kapoor, H. (2021, July). Who cares about the outgroup? Political Ideology, Empathy, and Moral Decision-Making. Paper presented at the _2021 Annual Scientific Meeting of the International Society of Political Psychology_ [(Preregistration)](https://osf.io/sfh93) [(Preprint)](https://psyarxiv.com/4es5u/)</li>

<li> Montilla, J., **Puthillam, A.**, Kapoor, H. (2021, June). Guidelines on including non-WEIRD populations in psychological science. Hackathon at the _Society for the Improvement of Psychological Science meeting_, 2021. [Hackathon] [(Materials)](https://osf.io/vm3sd/).</li>

<li> **Puthillam, A.** (2021, June). Too WEIRD, Too Fast: Preprints about the coronavirus pandemic in psychological science: Wave 2. Lightning Talk at the _Society for the Improvement of Psychological Science meeting_, 2021 [(Lightning Talk)](https://osf.io/j5x87/). [(Slides)](https://mfr.osf.io/render?url=https://osf.io/ut647/?direct%26mode=render%26action=download%26mode=render) [(Transcript)](https://mfr.osf.io/render?url=https://osf.io/k3txa/?direct%26mode=render%26action=download%26mode=render)</li>

<li> Ticku, A., **Puthillam, A.**, & Kapoor, H. (2021, May). How risky is it to not wear a mask? Moral emotions increase risk perception and public health behaviours during the Coronavirus epidemic. [Flash talk paper] _2021 APS Virtual Convention_. Virtual. [(Preregistration)](https://mfr.osf.io/render?url=https://osf.io/k3txa/?direct%26mode=render%26action=download%26mode=render)</li>

<li> Ticku, A., **Puthillam, A.**, & Kapoor, H. (2021, May). Licence to litter: The moderated mediating role of environmental values and moral emotions in the relationship between past moral behaviour and intended pro-environmental behaviours. Research proposal poster presentation at the _2021 APS Virtual Convention_. Virtual[(OSF)](https://mfr.osf.io/render?url=https://osf.io/k3txa/?direct%26mode=render%26action=download%26mode=render)</li>

<li> Kapoor, H. & **Puthillam, A.** (2021, April). Insights from Psychological Science and COVID-19 in India. Showcase at _COVID-19 Research Network Conference_. [(Video)](https://www.youtube.com/watch?v=rjrcDf_SR0Y)</li>

<li> **Puthillam, A.**, & Kapoor, H. (2021, February). Are you useful to me? How the Dark Triad Assesses benefits and experiences gratitude. Poster presented at the _2020 SPSP Virtual Annual Convention_. [(Working paper)](https://psyarxiv.com/5tguf/)</li>

<li> Ticku, A., **Puthillam, A.**, Kapoor, H., & De, K. (2021, January). What predicts COVID-19 compliant behaviors in India? Paper presented at the _3rd Annual UK Political Psychology Conference_.[(OSF)](https://psyarxiv.com/5tguf/)</li>

<li> **Puthillam, A.**, Karandikar, S., & Kapoor, H. (2020, July). Political Ideology in the Indian Context. Paper presented at the _43rd Annual Scientific Meeting of the International Society of Political Psychology_, Berlin, Germany. (Held virtually due to the COVID-19 pandemic).[(OSF)](https://psyarxiv.com/5tguf/)</li>

<li> **Puthillam, A.** (2016, December). The Perceptions of Moralities of Practicing and Non-Practicing Hindus in India. Paper presented at the _26th Annual Conference of the National Association of Psychology_, IIT Madras, India.</li>

<li> Debnath, A., Phansikar, M., **Puthillam, A.***, & Sengupta, P. (2016, December). Acceptance of gender atypical negative Behaviours: A Cross-sectional analysis. Paper Presented at the _26th Annual Conference of the National Association of Psychology_, IIT Madras, India.</li>

<li> Debnath, A., Phansikar, M., **Puthillam, A.***, & Sengupta, P. (2016, March). Cross Sectional Analysis of Gender Atypical Behaviours. Papers presented at the _International Conference on Womens' Studies and Social Sciences_, Goa, India</li>

_Note: *Authors contributed equally to this work. Authorship order determined appear alphabetically

</ol>

<center> <h1> Under Review/Preprints </h1></center>
<ol>

<li> **Puthillam, A.**, Mehta, N., Kapoor, H., Rezaei, & Lamba, N. (2022). Helpful or Not? Appraisal and Mechanisms of Prosociality in the Dark Triad [Preprint]</li>

<li> Mehta, N., Inamdar, V., **Puthillam, A.**, Chunekar, S., Kapoor, H., Tagat, A., & Subramanyam, D. Assessing the impact of COVID-19 on STEM researchers in India. _Welcome Open Research_ [awaiting peer review](https://wellcomeopenresearch.org/articles/7-157/v1)</li>

<li> **Puthillam, A.**, Mehta, N., Rezaei, S., Ticku, A., & Kapoor, H. Dutiful Citizens: Predictors of COVID-19 Policy Compliant Behavior in India. [under review at _Political Psychology_]</li>

<li> **Puthillam, A.** & Kapoor, H. (2021).They caused the pandemic! Conspiratorial blame, political beliefs, trust, and health behaviors during the COVID-19 pandemic [Preprint](https://psyarxiv.com/frgzq)</li>

<li> **Puthillam, A.**, Kapoor, H., & Karandikar, S. (2021). Beyond left and right: A scale to measure political ideology in India. [Preprint](https://static1.squarespace.com/static/53fe1e26e4b0e51709f9758f/t/600ac57a5d167e6f5356d961/1611318657113/Working+Paper_021-3_P.pdf)</li>

<li> **Puthillam, A.** & Kapoor, H. (2021). I vote NOTA: Ideological Expanses of Partisanship in India. [Preprint](https://psyarxiv.com/n6hek/)</li>

<li> **Puthillam, A.** & Kapoor, H. (2021). How are you useful to me? The relationship between dark triad and perception of help in prosocial situations. [Preprint](http://osf.io/5tguf)</li>

<li> **Puthillam, A.**, Karandikar, S., & Kapoor, H. (2019). Winner Takes All (the Gossip): Conversations in the reality show “Bigg Boss.” [Preprint](http://osf.io/8rvhe)</li>




