---
title: Research Output
author: Arathy
date: January 1, 2024
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

<center>

<h1>Peer-Reviewed Publications</h1>

</center>

1.  Kapoor, H., Rezaei, S., Gurjar, S., Tagat, A., George, D, Budhwar, Y. & **Puthillam, A.** (2023). Does incentivization promote sharing \"true\" content online?. *HKS Misinformation Review*. <https://doi.org/10.37016/mr-2020-120>

2.  **Puthillam, A.,** Montilla Doble, L. J., Delos Santos, J. I., Elsherif, M. M., Steltenpohl, C. N., Moreau, D.,\...& Kapoor, H. (2023). Guidelines to Improve Internationalization in the Psychological Sciences. *Personality and Social Psychology Compass*. <https://doi.org/10.1111/spc3.12847>

3.  **Puthillam, A.** (2023). Too WEIRD, Too Fast? Preprints about COVID-19 in Psychology. *Collabra: Psychology*9(1):74331. <https://doi.org/10.1525/collabra.74331>

4.  Azevedo, F., Pavlović, T.,... **Puthillam, A.** ... Sampaio, W. M. (2022). Social and moral psychology of COVID-19 across 69 countries. *Scientific Data, 10*(272). <https://doi.org/10.1038/s41597-023-02080-8>

5.  Pavlović, T.,... **Puthillam, A.** ... Van Bavel, J.J (2022). Predicting attitudinal and behavioral responses to COVID-19 pandemic using machine learning. *PNAS Nexus, 1*(3), pgac093. $$<https://doi.org/10.1093/pnasnexus/pgac093>$$$$<https://doi.org/10.1093/pnasnexus/pgac093>$$

6.  van Bavel, J.J. ... **Puthillam, A.** ... Boggio, P.S. (2022). National identity predicts public health support during a global pandemic. *Nature Communications, 13*(517). <https://doi.org/10.1038/s41467-021-27668-9>

7.  **Puthillam, A.**, Parekh, A., & Kapoor, H. (2021). How do relationships to victims and perpetrators affect the advice to report rape in India? *Violence against Women*. <https://doi.org/10.1177/10778012211005565>

8.  **Puthillam, A.**, Parekh, A., Karandikar, S., Kapoor, H. (2021). Gratitude blindness: How does the dark triad experiences gratitude? *Personality and Individual Differences*, 168, 110309. <https://doi.org/10.1016/j.paid.2020.110309>

9.  **Puthillam, A.**, & Karandikar, S. (2020). Watching disgustedly? Game of Thrones and disgust sensitivity. *Psychological Reports*. <https://doi.org/10.1177/0033294120957245>

10. **Puthillam, A.**, Karandikar, S., & Kapoor, H. (2019). I see how you feel: How the dark triad recognizes emotions. *Current Psychology*, 1-8. <doi:10.1007/s12144-019-00359-x>

11. Debnath, A., Phansikar, M., **Puthillam, A.**\*, & Sengupta, P. (2016). Cross sectional analysis of gender atypical behaviours. *Social Sciences International Research Journal* 2(1), 378-381.

\*Authors contributed equally to the work. Authorship order determined appear alphabetically

<center>

<h1>Conference Presentations</h1>

</center>

1.  Kapoor, H., Rezaei, S., Gurjar, S., Tagat, A., George, D., Budhwar,Y. & **Puthillam, A**. (2023, February). Does Incentivization Promote Sharing of "Good" Content Online? $$Poster$$ Society for Social and Personality Psychology.

2.  Mahadeshwar, H., Mehta, N., Gurjar, S., Kapoor, H., & **Puthillam, A**. (2023, February). . Does Incentivization Promote Sharing of "Good" Content Online? $$Poster$$ Society for Social and Personality Psychology.

3.  **Puthillam, A.** & Kapoor, H. (2022, July). Social and personality correlates of political ideology in India. Paper to be presented at the *Annual Meeting of the International Society for Political Psychology* $$to be presented virtually$$.

4.  **Puthillam, A.** & Kapoor, H. (2022, July). Partisanship and vaccine hesitancy in India. Blitz to be presented at the *Annual Meeting of the International Society for Political Psychology* $$to be presented virtually$$

5.  Ghai, S., Adetula, A., **Puthillam, A.**, Salvador, C., Kapoor, H., Atari, M., Saab, R (2022, June). A global diversity hackathon: Crowdsourcing diverse perspectives from the global south. $$Hackathon$$ at the Society for the Improvement of Psychological Science meeting, 2022. $$presented virtually$$

6.  **Puthillam, A**. & Kapoor, H. (2022, February). Partisanship and mobility behaviours during COVID-19 in India. Poster to be presented at the 2022 *SPSP Virtual Annual Convention*. $$Accepted$$

7.  Ticku, A., et al (2022, February). Pro-environmental behaviors. Poster to be presented at the 2022 *SPSP Virtual Annual Convention*. $$Accepted$$

8.  **Puthillam, A.** & Kapoor, H. (2021, November). Beyond left and right: Political psychology in India. Poster presented at the *Harvard Women in Psychology Trends in Psychology Summit*.

9.  **Puthillam, A.**, & Kapoor, H. (2021, October). Who cares about the outgroup? Political Ideology, Intergroup Empathy, and Moral Decision-Making. Cross-country proposal presented at the *Psychological Science Accelerator Conference 2021* [(Preregistration)](https://osf.io/sfh93)

10. Montilla, J., **Puthillam, A.**, Kapoor, H. (2021, October). Guidelines on including non-WEIRD populations in psychological science. Paper to be presented at the 60th Annual Conference of the Taiwan Psychological Association $$based on a previous hackathon$$ $$Hackathon Materials$$(<https://osf.io/vm3sd/>)

11. **Puthillam, A.** & Kapoor, H. (2021, October). Role of psychology in combating misinformation. Conversation at *The Centre for Internet and Society's Seminar Series on Information Disorders*.

12. **Puthillam, A.**, & Kapoor, H. (2021, July). They caused the pandemic! The mediating role of conspiratorial blame on the relationship between political ideology and risk perception. Paper presented as a part of the symposium "The psychological underpinnings of believing and communicating COVID-19 conspiracies" for presentation at the *2021 Annual Scientific Meeting of the International Society of Political Psychology* [(Preregistration)](https://osf.io/td39c/)

13. **Puthillam, A.**, & Kapoor, H. (2021, July). Who cares about the outgroup? Political Ideology, Empathy, and Moral Decision-Making. Paper presented at the *2021 Annual Scientific Meeting of the International Society of Political Psychology* [(Preregistration)](https://osf.io/sfh93) [(Preprint)](https://psyarxiv.com/4es5u/)

14. Montilla, J., **Puthillam, A.**, Kapoor, H. (2021, June). Guidelines on including non-WEIRD populations in psychological science. Hackathon at the *Society for the Improvement of Psychological Science meeting*, 2021. $$Hackathon$$ $$(Materials)$$(<https://osf.io/vm3sd/>).

15. **Puthillam, A.** (2021, June). Too WEIRD, Too Fast: Preprints about the coronavirus pandemic in psychological science: Wave 2. Lightning Talk at the *Society for the Improvement of Psychological Science meeting*, 2021 [(Lightning Talk)](https://osf.io/j5x87/). [(Slides)](https://mfr.osf.io/render?url=https://osf.io/ut647/?direct%26mode=render%26action=download%26mode=render) [(Transcript)](https://mfr.osf.io/render?url=https://osf.io/k3txa/?direct%26mode=render%26action=download%26mode=render)

16. Ticku, A., **Puthillam, A.**, & Kapoor, H. (2021, May). How risky is it to not wear a mask? Moral emotions increase risk perception and public health behaviours during the Coronavirus epidemic. Flash talk paper presentation at the *2021 APS Virtual Convention*. Virtual. [(Preregistration)](https://mfr.osf.io/render?url=https://osf.io/k3txa/?direct%26mode=render%26action=download%26mode=render)

17. Ticku, A., **Puthillam, A.**, & Kapoor, H. (2021, May). Licence to litter: The moderated mediating role of environmental values and moral emotions in the relationship between past moral behaviour and intended pro-environmental behaviours. Research proposal poster presentation at the *2021 APS Virtual Convention*. Virtual[(OSF)](https://mfr.osf.io/render?url=https://osf.io/k3txa/?direct%26mode=render%26action=download%26mode=render)

18. Kapoor, H. & **Puthillam, A.** (2021, April). Insights from Psychological Science and COVID-19 in India. Showcase at *COVID-19 Research Network Conference*. [(Video)](https://www.youtube.com/watch?v=rjrcDf_SR0Y)

19. **Puthillam, A.**, & Kapoor, H. (2021, February). Are you useful to me? How the Dark Triad Assesses benefits and experiences gratitude. Poster presented at the *2020 SPSP Virtual Annual Convention*. [(Working paper)](https://psyarxiv.com/5tguf/)

20. Ticku, A., **Puthillam, A.**, Kapoor, H., & De, K. (2021, January). What predicts COVID-19 compliant behaviors in India? Paper presented at the *3rd Annual UK Political Psychology Conference*.[(OSF)](https://psyarxiv.com/5tguf/)

21. **Puthillam, A.**, Karandikar, S., & Kapoor, H. (2020, July). Political Ideology in the Indian Context. Paper presented at the *43rd Annual Scientific Meeting of the International Society of Political Psychology*, Berlin, Germany. (Held virtually due to the COVID-19 pandemic).[(OSF)](https://psyarxiv.com/5tguf/)

22. **Puthillam, A.** (2016, December). The Perceptions of Moralities of Practicing and Non-Practicing Hindus in India. Paper presented at the *26th Annual Conference of the National Association of Psychology*, IIT Madras, India.

23. Debnath, A., Phansikar, M., **Puthillam, A.**\*, & Sengupta, P. (2016, December). Acceptance of gender atypical negative Behaviours: A Cross-sectional analysis. Paper Presented at the *26th Annual Conference of the National Association of Psychology*, IIT Madras, India.

24. Debnath, A., Phansikar, M., **Puthillam, A.**\*, & Sengupta, P. (2016, March). Cross Sectional Analysis of Gender Atypical Behaviours. Papers presented at the *International Conference on Womens' Studies and Social Sciences*, Goa, India

-   Authors contributed equally to this work. Authorship order determined appear alphabetically

<center>

<h1>Under Review/Preprints</h1>

</center>

1.  **Puthillam, A.**, Kapoor, H., Rezaei, S., Gurjar, S., Tagat, A., George, D., & Budhwar, Y. (2022). Does Incentivization Promote Sharing "Good" Content Online? $$Preprint$$

2.  **Puthillam, A.**, Montilla Doble, L. J., Delos Santos, J. I., Elsherif, M. M., Steltenpohl, C. N., Moreau, D., ... Kapoor, H. (2022). Guidelines to Improve Internationalization in Psychological Science $$Preprint$$ (invited for resubmission)

3.  **Puthillam, A.**, Mehta, N., Kapoor, H., Rezaei, & Lamba, N. (2022). Helpful or Not? Appraisal and Mechanisms of Prosociality in the Dark Triad $$Preprint$$ $$Preregistration$$.

4.  Mehta, N., Inamdar, V., **Puthillam, A.**, Chunekar, S., Kapoor, H., Tagat, A., & Subramanyam, D. Assessing the impact of COVID-19 on STEM researchers in India. *Welcome Open Research* [awaiting peer review](https://wellcomeopenresearch.org/articles/7-157/v1)

5.  **Puthillam, A.**, Mehta, N., Rezaei, S., Ticku, A., & Kapoor, H. Dutiful Citizens: Predictors of COVID-19 Policy Compliant Behavior in India. $$under review at *Political Psychology*$$

6.  **Puthillam, A.** & Kapoor, H. (2021).They caused the pandemic! Conspiratorial blame, political beliefs, trust, and health behaviors during the COVID-19 pandemic [Preprint](https://psyarxiv.com/frgzq)

7.  **Puthillam, A.** (2021). Too WEIRD, Too Fast? Preprints about COVID-19 in Psychology (invited for resubmission). [Preprint](https://psyarxiv.com/jeh84) $$invited for resubmission at Collabra: Psychology$$

8.  **Puthillam, A.**, Kapoor, H., & Karandikar, S. (2021). Beyond left and right: A scale to measure political ideology in India. [Preprint](https://static1.squarespace.com/static/53fe1e26e4b0e51709f9758f/t/600ac57a5d167e6f5356d961/1611318657113/Working+Paper_021-3_P.pdf)

9.  **Puthillam, A.** & Kapoor, H. (2021). I vote NOTA: Ideological Expanses of Partisanship in India. [Preprint](https://psyarxiv.com/n6hek/)

10. **Puthillam, A.** (2021). What makes you "Ew!"? Cross-National Measurement Invariance in Disgust Sensitivity. [Preprint](https://psyarxiv.com/svc53/)

11. **Puthillam, A.** & Kapoor, H. (2021). Who cares about the outgroup? Political ideology, empathy, and moral decision-making [Preprint](https://psyarxiv.com/4es5u/)

12. Ticku, A., **Puthillam, A.**, & Kapoor, H., (2021). Empathy across cultures: Critiquing the generalized understanding and measurement of empathy

13. Ticku, A., **Puthillam, A.**, & Kapoor, H. (2020). How risky is it to not wear a mask? How risky is it to not wear a mask? Moral emotions are associated with risk perception and public health behaviours during the coronavirus epidemic. [Preregistration](https://osf.io/n4bpm/) [Preprint](https://psyarxiv.com/vtxuk)

14. **Puthillam, A.** & Kapoor, H. (2021). How are you useful to me? The relationship between dark triad and perception of help in prosocial situations. [Preprint](http://osf.io/5tguf)

15. **Puthillam, A.**, Karandikar, S., & Kapoor, H. (2019). Winner Takes All (the Gossip): Conversations in the reality show "Bigg Boss." [Preprint](http://osf.io/8rvhe)
